### PR TITLE
Fix bean definitions for Spring 4.1

### PR DESCRIPTION
**Pull request by curtisvo**

### CODE REVIEW

**Comment by bjones86** [comment]
LGTM, thanks @curtisvo.

Just for future reference, you should prefix your commit message with the JIRA ticket ID, like this:

"EVALSYS-1481: fix bean definitions for Spring 4.1"

Don't worry about re-wording this one though, we can fix it up when we merge. Just an FYI for future PRs :)

**Comment by bjones86** [comment]
Oh, I just realized this PR is targetting the 11.x branch. Can you reissue this against master? We can cherry-pick it back to the 11.x branch after it's merged to master.

**Comment by curtisvo** [comment]
I targetted 11.x because the problem doesn't exist in master.

**Comment by bjones86** [comment]
Ah, I see now. Thanks for clarifying.

**Pull request merged**
