### PR TITLE
EVALSYS-1526 - Tests are failing in evalsys after recent change

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
Yeah, really should figure out how to get this into travis. I *think* now that we're publishing 12-SNAPSHOT artifacts this should be possible, just haven't had time.

**Comment by ottenhoff** [comment]
Get into travis means use travis as part of the PR workflow? If yes, I can take a quick look

**Comment by jonespm** [comment]
Yeah, get set up on travis.

But we couldn't get this on travis before because in order to build evaluation it needs apis from core Sakai built and in the repository first. A few weeks ago I got jenkins to deploy 12-SNAPSHOT artifacts to maven snapshot so if you build with

mvn clean install -P snapshots

Then it should use the snapshots from the repository rather than requiring local artifacts. So that might be all that needs to be configured additionally in the travis.yml (well along with the other stuff in the core sakai travis.yml)

**Comment by jonespm** [comment]
Hmm, the problem is it still needs master though. So maybe something in the beforeInstall would have to get that master setup? Or maybe this profile with the snapshots repository could be setup inside the evaluation top level top.

**Pull request merged**
