### PR TITLE
EVALSYS-1522: error after survey with NavBarRenderer (probably anonymous) via URL

### PR DESCRIPTION
**Pull request by bjones86**
https://jira.sakaiproject.org/browse/EVALSYS-1522

### CODE REVIEW

**Comment by bjones86** [comment]
@jonespm do you mind testing this one? I tested locally but I'm getting a SQL exception that I think might be unrelated. Maybe I need to update my database or something, not sure, but I don't have time to try to investigate more today.

If you don't get around to it, I'll get back at it tomorrow. Cheers.

**Comment by jonespm** [comment]
Yeah, might be, I'm testing right now. If you were using the mariadb driver the current version(s) were causing random SQL errors like this. I switched to all MySQL.

**Comment by jonespm** [comment]
Okay, there are no more errors in the UI so that's good, and it also makes the question save so that's even better. There are still 2 warnings with stack traces that don't look too good but these are part of a try catch. This was when using an adhoc group. Maybe this exception (IdUnusedException) can just be lowered in severity or this message in general can. I can create a new issue for this though. Since it's not as big a deal.

```
22-Jun-2017 16:32:04.998 WARN [http-nio-8080-exec-4] org.sakaiproject.evaluation.logic.externals.ExternalHierarchyLogicImpl.getNodesAboveEvalGroup Could not find site or section by ID
org.sakaiproject.exception.IdUnusedException id: adhoc-group:1
	at org.sakaiproject.site.impl.BaseSiteService.getDefinedSite(BaseSiteService.java:675)
	at org.sakaiproject.site.impl.BaseSiteService.getSite(BaseSiteService.java:753)
	at org.sakaiproject.evaluation.logic.externals.ExternalHierarchyLogicImpl.getNodesAboveEvalGroup(ExternalHierarchyLogicImpl.java:601)
```

**Comment by jonespm** [comment]
Just changed the log level for this one in #75

**Comment by bjones86** [comment]
Yep, mariadb driver :(

**Pull request merged**
