### PR TITLE
EVALSYS-1006: Allow templates to be shared. Patch done by Nick Wilson…

### PR DESCRIPTION
**Pull request by danielmerino**
… from Oxford.

### CODE REVIEW

**Comment by lardo-de-arnaud** [comment]
The patch you've applied is for EVALSYS-1040 not EVALSYS-1006. I believe the wrong Jira has been closed but the correct patch applied. The pull request is against the wrong Jira.

**Comment by lardo-de-arnaud** [comment]
We had mentioned the wrong EVALSYS jira in GIT, sorry about that.

**Comment by danielmerino** [comment]
I didn't even know that EVALSYS-1006 did exist... Sorry for that.

Is there any GitHub guru out there that could change this merged branch to be related with EVALSYS-1006 instead of EVALSYS-1040? I can reopen and close the JIRA tickets, but no idea how to fix the merge here (neither if I have privileges to do it).

**Comment by buckett** [comment]
We could go back an edit history, the problem is that if anyone currently has a checkout and uses that checkout to create a new pull request it will always fail without getting fetched and rebased first.

**Comment by jonespm** [comment]
Yeah right, if we change the past, we'd have to force push against this right? Which is something re *really* want to avoid anyway. I feel like it's going to have to stay wrong in the message.

**Comment by jonespm** [comment]
I think what it means is you're going to have to fix EVALSYS-1006 so both fixes are in here! ;) I've reopened this one on jira.

**Pull request merged**
