### PR TITLE
EVALSYS-1573 Sakai 20. Jun'19 Upgrade libraries and dependencies

### PR DESCRIPTION
**Pull request by axxter99**

### CODE REVIEW

**Comment by axxter99** [comment]
@mpellicer @ottenhoff

**Comment by mpellicer** [comment]
@axxter99 looks good but is not resolving the jdom2 version properly, the build is broken :(

**Comment by axxter99** [comment]
@mpellicer evaluation master:

[ERROR]   The project org.sakaiproject.evaluation:sakai-evaluation-impl:20-SNAPSHOT (/home/dhorwitz/git/evaluation/sakai-evaluation-impl/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for jdom:jdom:jar is missing. @ line 105, column 21
[ERROR] 
[ERROR] 

EVALSYS-1573 branch mvn OK

**Comment by mpellicer** [comment]
Thanks @axxter99, I've launched the build again and works fine.

Unfortunately, I don't have permissions to merge this PR.

**Pull request merged**
