### PR TITLE
EVALSYS-969 - Saving templates with bad markup silently fails. Emails…

### PR DESCRIPTION
**Pull request by danielmerino**
… are not sent and users don't notice.

### CODE REVIEW

**Comment by danielmerino** [comment]
I have done a patch that throws an IllegalArgumentException when the check fails, but I haven't been able to show a proper error message to user in the HTML page. It seems that error messages are handled by AJAX js embedded inside RSF templates and it's really hard for me to figure out how to do that.

Anyway, it's better to show a general error message when the template is bad than no message at all, don't you think? The message can be added in another JIRA if some RSF guru is available out there.

**Comment by jonespm** [comment]
Hey @danielmerino , I was trying to test this but I couldn't get anything to fail. Do you have a test case that will fail the template that you can add to the jira? I feel like this code duplication between checkFreemarkerTextTemplate and processFreemarkerTextTemplate could also be reduced here. Maybe just have checkFreemarkerTextTemplate call processFreemarkerTextTemplate catching the RuntimeException and returning true/false?

**Comment by danielmerino** [comment]
@jonespm You are right, the code can be improved. I have done some changes, please do a new review.

I have added a test plan in the JIRA EVALSYS-969.

**Comment by jonespm** [comment]
Looking good, thanks! I added another commit to this PR that will add the error message when the save fails. It looks good to me in testing! Adding errors to RSF is just adding a new "TargettedMessage" there with an error severity. 

image

**Comment by danielmerino** [comment]
@jonespm your commit with the error message works great when saving a template from "My Email Templates" but it still doesn't work when saving a template from a single evaluation's settings.
In fact, your capture of the error in EmailTemplateWBL.java has the collateral effect that no error message is shown at all when a bad template is saved (though it is not saved, but user doesn't notice)

**Comment by jonespm** [comment]
I guess I didn't test both places, there are way too many places in Evaluation. I'm guessing since I don't rethrow the exception and it doesn't deal with the template messages nothing is printed up in this other class. I'll put in a new PR. Thanks.

**Comment by danielmerino** [comment]
Yes, I have done a quick test and rethrowing the IllegalArgumentException after setting the message in EmailTemplateWBL.java works in both cases (and in settings the message also is printed up, yeah!). The only issue is that the stacktrace is printed in Tomcat's logs, but I think this is not a big deal, is it?

**Comment by jonespm** [comment]
Yeah, that seems fine to me too for the user side it's fine and the server side it's fine too. I don't think this will happen often and I feel like the fix for this (stack trace) might be to change the log to be in a debug in PonderUtilCore rather than the WARN that it is now. and not a big deal. I'll do the rethrow fix right now.

**Comment by jonespm** [comment]
PR on #79

**Pull request merged**
