### PR TITLE
EVALSYS-1519: added autosize.js library to handle resizing of textareas

### PR DESCRIPTION
**Pull request by slampunk**
Replaced jQuery elastic library with autosize.js, fixing issue of window width constantly changing for certain viewports (specifically mobile devices)

### CODE REVIEW

**Comment by jonespm** [comment]
Sorry for not getting back, the only suggestion I'd make is to use the autosize webjar rather than including it here.

I've never tried this for a contrib project but you should be able to just include it as a dependency and then just link to it as it'll be deployed to WEB-INF/lib/

```
diff --git a/sakai-evaluation-tool/pom.xml b/sakai-evaluation-tool/pom.xml
index d8f8c48..2d09c13 100644
--- a/sakai-evaluation-tool/pom.xml
+++ b/sakai-evaluation-tool/pom.xml
@@ -200,6 +200,11 @@
             <version>4.5</version>
             <scope>test</scope>
         </dependency>
+        <dependency>
+            <groupId>org.webjars.bower</groupId>
+            <artifactId>autosize</artifactId>
+            <version>3.0.21</version>
+        </dependency>
     </dependencies>
 
     <build>

```

```
    <script src="webjars/autosize/3.0.21/autosize.js" type="text/javascript"></script>
``` 

https://www.webjars.org/documentation#servlet3
https://mvnrepository.com/artifact/org.webjars.bower/autosize/3.0.21

**Comment by slampunk** [comment]
Thanks, that makes much more sense than the way I did it.

I'll try this over the weekend.

**Comment by ottenhoff** [comment]
Hi @slampunk, any luck with using the webjar version?

**Comment by slampunk** [comment]
Hi @ottenhoff,

I attempted the webjar, but I couldn't reference it on the client side properly. The autosize.js library was built into the webjar though.

Do you mind if I decline this PR while I figure out the linking, and submit another PR afterwards?

**Comment by jonespm** [comment]
I added and tested the webjar version on #78. It looks like I had to use the "servlet 2" version idea because we're skipping jar scanning so they're not registered by tomcat, even if I updated the web.xml in evaluation to 3.0 (it's currently 2.4). None of the examples on that page worked either the way I have tomcat configured for Sakai. That PR worked though.

**Comment by ottenhoff** [comment]
Okay closing in favor of #78

**Pull request closed without merging**
